language: node_js
node_js:
  - '12.16.2'
sudo: true

addons:
    chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
